### ISSUE TITLE
Requesting Attachments of Documents 

### ISSUE THREAD

**Issue by Shyamnath-tech** [GowthamsGit/Whatsup_Development#6]
Dear Gowtham,

It would be great if the app is capable of attaching the documents as well. Kindly add this feature.

**Comment by GowthamsGit** [comment]
Dear Shyam, Thanks for suggesting this feature. We will add and let you know.

**Comment by GowthamsGit** [comment]
Dear Shyam, Thanks for your valuable suggestion. This feature is going to make our product great.
